[package]
name = "client-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
clap = "2.*"
time = "^0.2.23"
