[package]
name = "client-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
bincode = "*"
tokio-util = "*"
clap = "2.*"
chrono = { version = "^0.4.1", features = ["serde", "rustc-serialize"] }
